services:
  
  yjv.report_rendering.column_type_registry_extension:
    class: Yjv\ReportRendering\Factory\Extension\DependencyInjectionExtension
    arguments: ['@service_container']
  
  yjv.report_rendering.column_type_registry:
    class: Yjv\ReportRendering\Factory\TypeRegistry
    calls:
      - [addExtension, ['@yjv.report_rendering.column_type_registry_extension']]
    
  yjv.report_rendering.column_type_resolver:
    class: Yjv\ReportRendering\Factory\TypeResolver
    arguments: ['@yjv.report_rendering.column_type_registry']
  
  yjv.report_rendering.column_factory:
    class: Yjv\ReportRendering\Renderer\Grid\Column\ColumnFactory
    arguments: 
      - '@yjv.report_rendering.column_type_resolver'
      - '@yjv.report_rendering.data_transformer_registry'
  
  #types
  
  yjv.report_rendering.column_type:
    class: Yjv\ReportRendering\Renderer\Grid\Column\Extension\Core\Type\ColumnType
    tags:
      - { name: yjv.report_rendering.column_type, alias: column }
  
  yjv.report_rendering.raw_column_type:
    class: Yjv\ReportRendering\Renderer\Grid\Column\Extension\Core\Type\RawColumnType
    tags:
      - { name: yjv.report_rendering.column_type, alias: raw_column }
  
  yjv.report_rendering.property_path_column_type:
    class: Yjv\ReportRendering\Renderer\Grid\Column\Extension\Core\Type\PropertyPathType
    tags:
      - { name: yjv.report_rendering.column_type, alias: property_path }