services:
  
  yjv.report_rendering.column_type_registry:
    class: Yjv\ReportRendering\Factory\TypeRegistry
    
  yjv.report_rendering.column_type_resolver:
    class: Yjv\ReportRendering\Factory\TypeResolver
    arguments: ['@yjv.report_rendering.report_type_registry']
  
  yjv.report_rendering.column_factory:
    class: Yjv\Bundle\ReportRenderingBundle\Renderer\Grid\Column\ColumnFactory
    arguments: 
      - '@yjv.report_rendering.column_type_resolver'
      - '@yjv.report_rendering.data_transformer_registry'
  
  #types
  
  yjv.report_rendering.column:
    class: Yjv\Bundle\ReportRenderingBundle\Renderer\Grid\Column\Type\ColumnType
    tags:
      - { name: 'yjv.column_type' }
  
  yjv.report_rendering.raw_column:
    class: Yjv\Bundle\ReportRenderingBundle\Renderer\Grid\Column\Type\RawColumnType
    tags:
      - { name: 'yjv.column_type' }
  
  yjv.report_rendering.property_path_column:
    class: Yjv\Bundle\ReportRenderingBundle\Renderer\Grid\Column\Type\PropertyPathType
    tags:
      - { name: 'yjv.column_type' }