services:
  
  yjv.report_rendering.widget_renderer:
    class: Yjv\ReportRendering\Widget\WidgetRenderer
    arguments: ['@templating']
    
  yjv.report_rendering.twig_extension:
    class: Yjv\ReportRendering\Twig\ReportRenderingExtension
    tags:
      - { name: twig.extension }

  yjv.report_rendering.data_escaper:
    class: Yjv\ReportRendering\Data\DataEscaper